title = "Org Secret Scanning Rules"
version = 3

[extend]
useDefault = true

[[rules]]
id = "generic-password-rule"
description = "Generic password assignment"
regex = '''(?i)(?:password|passwd|pass|secret|sec)\s*[:=]\s*["']?[A-Za-z0-9!@#$%^&*()_+\-]{8,}["']?'''
tags = ["password", "generic"]
severity = "high"
